// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductoAPI.Models;

#nullable disable

namespace ProductoAPI.Migrations
{
    [DbContext(typeof(ProductoContext))]
    partial class ProductoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductoAPI.Models.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Categoria = "Electronica",
                            Descripcion = "Una Laptop de alto rendimiento",
                            Nombre = "Laptop"
                        },
                        new
                        {
                            id = 2,
                            Categoria = "Electronica",
                            Descripcion = "Samsung Galaxy Note 20",
                            Nombre = "Smartphone"
                        },
                        new
                        {
                            id = 3,
                            Categoria = "Muebles",
                            Descripcion = "Silla Gaming corsair",
                            Nombre = "Silla"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
