// <auto-generated />
using LibroAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibroAPI.Migrations
{
    [DbContext(typeof(LibroContext))]
    partial class LibroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibroAPI.Models.Libro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AnioPublicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AnioPublicacion = "1967",
                            Autor = "Gabriel Garcia Marquez",
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            id = 2,
                            AnioPublicacion = "1605",
                            Autor = "Miguel de Cervantes",
                            Titulo = "Don Quijote de la mancha"
                        },
                        new
                        {
                            id = 3,
                            AnioPublicacion = "1985",
                            Autor = "Gabriel Garcia Marquez",
                            Titulo = "El amor en los tiempos de Colera"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
